// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace de.dhoffmann.mono.andnaviki
{
	
	
	public partial class Resource
	{
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f050001
			public const int CalcRouteType_array = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int Countries_array = 2131034112;
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060003
			public const int LinearLayout02 = 2131099651;
			
			// aapt resource value: 0x7f060002
			public const int ScrollView01 = 2131099650;
			
			// aapt resource value: 0x7f06000e
			public const int btnCalulateRoute = 2131099662;
			
			// aapt resource value: 0x7f060009
			public const int btnMyLocationStart = 2131099657;
			
			// aapt resource value: 0x7f060004
			public const int btnNewRoute = 2131099652;
			
			// aapt resource value: 0x7f060007
			public const int btnQuit = 2131099655;
			
			// aapt resource value: 0x7f060005
			public const int btnRoutes = 2131099653;
			
			// aapt resource value: 0x7f060006
			public const int btnSettings = 2131099654;
			
			// aapt resource value: 0x7f06000c
			public const int etMyLocationDestination = 2131099660;
			
			// aapt resource value: 0x7f06000b
			public const int etMyLocationStart = 2131099659;
			
			// aapt resource value: 0x7f060008
			public const int etUrl = 2131099656;
			
			// aapt resource value: 0x7f06000a
			public const int llCProviderContainr = 2131099658;
			
			// aapt resource value: 0x7f060001
			public const int lstProvider = 2131099649;
			
			// aapt resource value: 0x7f06000d
			public const int spnCalcRouteType = 2131099661;
			
			// aapt resource value: 0x7f060000
			public const int spnCountry = 2131099648;
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int ProviderSelection = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Root = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int RoutesNew_File = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int RoutesNew_NavikiOrg = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int RoutesNew_Url = 2130903044;
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f04000a
			public const int CalcRouteType = 2130968586;
			
			// aapt resource value: 0x7f040009
			public const int Countries = 2130968585;
			
			// aapt resource value: 0x7f040000
			public const int app_name = 2130968576;
			
			// aapt resource value: 0x7f04000b
			public const int btnCalulateRoute = 2130968587;
			
			// aapt resource value: 0x7f04000f
			public const int btnFileImport = 2130968591;
			
			// aapt resource value: 0x7f040006
			public const int btnMyLocation = 2130968582;
			
			// aapt resource value: 0x7f040001
			public const int btnNewRoute = 2130968577;
			
			// aapt resource value: 0x7f040004
			public const int btnQuit = 2130968580;
			
			// aapt resource value: 0x7f040002
			public const int btnRoutes = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int btnSettings = 2130968579;
			
			// aapt resource value: 0x7f04000d
			public const int btnUrlImport = 2130968589;
			
			// aapt resource value: 0x7f04000e
			public const int lbFile = 2130968590;
			
			// aapt resource value: 0x7f040007
			public const int lbPostionDestination = 2130968583;
			
			// aapt resource value: 0x7f040005
			public const int lbPostionStart = 2130968581;
			
			// aapt resource value: 0x7f040008
			public const int lbRouteNewCalcType = 2130968584;
			
			// aapt resource value: 0x7f04000c
			public const int lbUrl = 2130968588;
			
			private String()
			{
			}
		}
	}
}
